apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: production
  labels:
    app: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: linuxacademycontent/gitops:hellov1.1
        ports:
        - containerPort: 80
